# --- SITE SETTINGS ---
title: Open Lunar
description: Hardware & Infrastructure Development Community
baseurl: "" 
url: "http://openlunarinfrastructure.com/" # Replace with your actual URL
theme: minima

# --- NAVIGATION TABS ---
# List the exact filenames of the pages you want in the top menu
header_pages:
  - about.md
  - projects.md
  - join.md

# --- FOOTER LINKS ---
minima:
  social_links:
    - { platform: github,   user_url: "https://github.com/orgs/Open-Lunar-Hardware-Community/repositories" }
    - { platform: YouTube,  user_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ&themeRefresh=1" }
